[package]
name = "day1"
version = "0.1.0"
authors = ["Doug Stephen <dljs.jr@dougstephenjr.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
