[package]
name = "day4"
version = "0.1.0"
authors = ["Doug Stephen <dstephen@ihmc.us>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.9"
regex = "1.5.5"
lazy_static = "1.4.0"